# 应用名称
spring:
  application:
    name: spring-cloud-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka1
#    prefer-ip-address: false
  client:
    # false表示不向注册中心注册自己，集群模式为true
    fetch-registry: true
    # false表示自己就是注册中心，集群模式为true
    register-with-eureka: true
    service-url:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka2:7002/eureka,http://eureka3:7003/eureka